url: https://ohrite.github.io
baseurl: /mobilization
title: National Mobilization for Reproductive Justice
description: Join the movement to defend the right of women and all people to control their own bodies.
future: true
logo: favicon.png

forms:
  newsletter:
    url: https://docs.google.com/forms/d/e/1FAIpQLSdnIpE2mlhieRnpUTK2KQM3bglCYdK1dlLxmYE6nNES4f4omw/formResponse
    fields:
      email: entry.859380513
  endorsement:
    url: https://docs.google.com/forms/u/1/d/e/1FAIpQLSclP5FezAcTEcYQyuU-f9i-50AvgciTDe8VPr5Cf7md3WzjKw/formResponse
    fields:
      email: entry.859380513
      organization_name: entry.754769655
      address: entry.1657888341
      website: entry.1713845971
      full_name: entry.1958360706
      email_address: entry.1596241086
      phone: entry.847401212

twitter:
  username: radicalwomenus
  card: summary

facebook:
  page: 18213462909

social:
  name: National Mobilization for Reproductive Justice
  links:
    - https://twitter.com/radicalwomenus
    - https://www.facebook.com/RadicalWomenUS

plugins:
  - jekyll-archives
  - jekyll-last-modified-at
  - jekyll-postcss
  - jekyll-seo-tag
  - jekyll-sitemap

postcss:
  cache: false

defaults:
  - scope:
      path: assets/**/*.pdf
    values:
      sitemap: false
  - scope:
      path: events/**/*.md
    values:
      sitemap: false
  - scope:
      path: press/**/*.md
    values:
      sitemap: false
  - scope:
      path: resources/**/*.md
    values:
      sitemap: false
  - scope:
      path: labor_involvement/**/*.md
    values:
      sitemap: false

jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
