source 'https://rubygems.org'

gem 'jekyll'
gem 'webrick'
gem 'jekyll-archives'
gem 'jekyll-favicon', git: 'https://github.com/jonchang/jekyll-favicon', ref: 'psych-4-fix'
gem 'jekyll-last-modified-at'
gem 'jekyll-postcss'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
